<a href="https://colab.research.google.com/github/prashantbkoli/Machine-Learning/blob/main/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd   # Import library:Used for creating and manipulating data tables (DataFrames).
import numpy as np    # Import library :Used for numerical operations and generating random values.
import warnings       #Used to control warning messages.
warnings.filterwarnings("ignore")

np.random.seed(42) #Ensures that every time the program runs, it generates the same random data.
def createdata():
  data = {
      'Age': np.random.randint(18, 70, size=20),
      'Salary': np.random.randint(30000, 120000, size=20),
      'Purchased': np.random.choice([0, 1], size=20),
      'Gender': np.random.choice(['Male', 'Female'], size=20),
      'City': np.random.choice(['New York', 'San Francisco', 'Los Angeles'], size=20)
  }

  df = pd.DataFrame(data)
  return df

df = createdata()
df.head(20)

    Age  Salary  Purchased  Gender           City
0    56   92955          1  Female  San Francisco
1    69   94925          0  Female  San Francisco
2    46   97969          0    Male       New York
3    32   35311          0  Female    Los Angeles
4    60  113104          0    Male  San Francisco
5    25   83707          0  Female  San Francisco
6    38  115305          0    Male  San Francisco
7    56   58693          0  Female  San Francisco
8    36  101932          0    Male  San Francisco
9    40   55658          1    Male  San Francisco
10   28  114478          1  Female    Los Angeles
11   28   48431          0    Male    Los Angeles
12   41   32747          1  Female  San Francisco
13   53   89150          1  Female    Los Angeles
14   57   95725          1  Female       New York
15   41  114654          1  Female  San Francisco
16   20   65773          0  Female       New York
17   39   97435          1  Female       New York
18   19   86886          0  Female  San Francisco
19   41   96803          1  Female    Los Angeles

In [ ]:

df.shape  #returns the dimensions (size) of the DataFrame in the form: rows n col

(20, 5)

When you have missing value in data

In [ ]:
# Introduce some missing values for demonstration
df.loc[5, 'Age'] = np.nan
df.loc[5, 'Salary'] = np.nan
df.head(10)

    Age    Salary  Purchased  Gender           City
0  56.0   92955.0          1  Female  San Francisco
1  69.0   94925.0          0  Female  San Francisco
2  46.0   97969.0          0    Male       New York
3  32.0   35311.0          0  Female    Los Angeles
4  60.0  113104.0          0    Male  San Francisco
5   NaN       NaN          0  Female  San Francisco
6  38.0  115305.0          0    Male  San Francisco
7  56.0   58693.0          0  Female  San Francisco
8  36.0  101932.0          0    Male  San Francisco
9  40.0   55658.0          1    Male  San Francisco

In [ ]:
# Simple Imputation (mean, median, mode) -
#Pros: Fast and straightforward.
#Cons: May introduce bias if missing data isn’t random. --Unfold data science mising data treatment
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].median(), inplace=True)
df.head(10)

         Age    Salary  Purchased  Gender           City
0  56.000000   92955.0          1  Female  San Francisco
1  69.000000   94925.0          0  Female  San Francisco
2  46.000000   97969.0          0    Male       New York
3  32.000000   35311.0          0  Female    Los Angeles
4  60.000000  113104.0          0    Male  San Francisco
5  42.105263   83707.0          0  Female  San Francisco
6  38.000000  115305.0          0    Male  San Francisco
7  56.000000   58693.0          0  Female  San Francisco
8  36.000000  101932.0          0    Male  San Francisco
9  40.000000   55658.0          1    Male  San Francisco

In [ ]:
# Introduce some missing values for demonstration
df.loc[5, 'Age'] = np.nan
df.loc[5, 'Salary'] = np.nan
df.head(10)

    Age    Salary  Purchased  Gender           City
0  56.0   92955.0          1  Female  San Francisco
1  69.0   94925.0          0  Female  San Francisco
2  46.0   97969.0          0    Male       New York
3  32.0   35311.0          0  Female    Los Angeles
4  60.0  113104.0          0    Male  San Francisco
5   NaN       NaN          0  Female  San Francisco
6  38.0  115305.0          0    Male  San Francisco
7  56.0   58693.0          0  Female  San Francisco
8  36.0  101932.0          0    Male  San Francisco
9  40.0   55658.0          1    Male  San Francisco

In [ ]:
df.shape

(20, 5)

In [ ]:
# Listwise deletion
#pros : Simple .
#Cons - loosing data
df_dropped = df.dropna()
df_dropped.head(10)

     Age    Salary  Purchased  Gender           City
0   56.0   92955.0          1  Female  San Francisco
1   69.0   94925.0          0  Female  San Francisco
2   46.0   97969.0          0    Male       New York
3   32.0   35311.0          0  Female    Los Angeles
4   60.0  113104.0          0    Male  San Francisco
6   38.0  115305.0          0    Male  San Francisco
7   56.0   58693.0          0  Female  San Francisco
8   36.0  101932.0          0    Male  San Francisco
9   40.0   55658.0          1    Male  San Francisco
11  28.0   48431.0          0    Male    Los Angeles

In [ ]:
df_dropped.shape

(18, 5)

In [ ]:
# Introduce some missing values for demonstration
df.loc[5, 'Age'] = np.nan
df.loc[5, 'Salary'] = np.nan
df.head(10)

    Age    Salary  Purchased  Gender           City
0  56.0   92955.0          1  Female  San Francisco
1  69.0   94925.0          0  Female  San Francisco
2  46.0   97969.0          0    Male       New York
3  32.0   35311.0          0  Female    Los Angeles
4  60.0  113104.0          0    Male  San Francisco
5   NaN       NaN          0  Female  San Francisco
6  38.0  115305.0          0    Male  San Francisco
7  56.0   58693.0          0  Female  San Francisco
8  36.0  101932.0          0    Male  San Francisco
9  40.0   55658.0          1    Male  San Francisco

In [ ]:
# Predictive Imputation - seach for MICE imputation as well -
#Pros: More accurate for complex patterns.
#Cons: Computationally intensive, may add noise with high variance.
from sklearn.impute import KNNImputer
knn_imputer = KNNImputer(n_neighbors=3)
df[['Age', 'Salary']] = knn_imputer.fit_transform(df[['Age', 'Salary']])

In [ ]:
df.head(10)

         Age    Salary  Purchased  Gender           City
0  56.000000   92955.0          1  Female  San Francisco
1  69.000000   94925.0          0  Female  San Francisco
2  46.000000   97969.0          0    Male       New York
3  32.000000   35311.0          0  Female    Los Angeles
4  60.000000  113104.0          0    Male  San Francisco
5  42.105263   83707.0          0  Female  San Francisco
6  38.000000  115305.0          0    Male  San Francisco
7  56.000000   58693.0          0  Female  San Francisco
8  36.000000  101932.0          0    Male  San Francisco
9  40.000000   55658.0          1    Male  San Francisco

In [ ]:
# Introduce some missing values for demonstration
df.loc[5, 'Age'] = np.nan
df.loc[5, 'Salary'] = np.nan
df.head(10)

    Age    Salary  Purchased  Gender           City
0  56.0   92955.0          1  Female  San Francisco
1  69.0   94925.0          0  Female  San Francisco
2  46.0   97969.0          0    Male       New York
3  32.0   35311.0          0  Female    Los Angeles
4  60.0  113104.0          0    Male  San Francisco
5   NaN       NaN          0  Female  San Francisco
6  38.0  115305.0          0    Male  San Francisco
7  56.0   58693.0          0  Female  San Francisco
8  36.0  101932.0          0    Male  San Francisco
9  40.0   55658.0          1    Male  San Francisco

In [ ]:
# Add indicator for missingness
#Pros: Allows the model to learn patterns of missingness.
#Cons: Can increase dimensionality and complexity.
df['Age_missing'] = df['Age'].isnull().astype(int)
df.head(10)

    Age    Salary  Purchased  Gender           City  Age_missing
0  56.0   92955.0          1  Female  San Francisco            0
1  69.0   94925.0          0  Female  San Francisco            0
2  46.0   97969.0          0    Male       New York            0
3  32.0   35311.0          0  Female    Los Angeles            0
4  60.0  113104.0          0    Male  San Francisco            0
5   NaN       NaN          0  Female  San Francisco            1
6  38.0  115305.0          0    Male  San Francisco            0
7  56.0   58693.0          0  Female  San Francisco            0
8  36.0  101932.0          0    Male  San Francisco            0
9  40.0   55658.0          1    Male  San Francisco            0

When you have Categorical Variables in data

In [ ]:
# Label Encoding
#Pros: Simple and space-efficient.
#Cons: Implies ordinal relationship, which may mislead models.
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df.head()

    Age    Salary  Purchased  Gender           City  Age_missing
0  56.0   92955.0          1       0  San Francisco            0
1  69.0   94925.0          0       0  San Francisco            0
2  46.0   97969.0          0       1       New York            0
3  32.0   35311.0          0       0    Los Angeles            0
4  60.0  113104.0          0       1  San Francisco            0

In [ ]:
# One-Hot Encoding
#Pros: Great for non-ordinal categories; maintains all category information.
#Cons: Increases dimensionality, particularly with many unique values.#
df = pd.get_dummies(df, columns=['City'], drop_first=True)
df.head()

,Age,Salary,Purchased,Gender,Age_missing,City_New York,City_San Francisco
0,56.0,92955.0,1,0,0,False,True
1,69.0,94925.0,0,0,0,False,True
2,46.0,97969.0,0,1,0,True,False
3,32.0,35311.0,0,0,0,False,False
4,60.0,113104.0,0,1,0,False,True

In [ ]:
df = createdata()

In [ ]:
# Ordinal Encoding
#Pros: Effective for ordinal data; captures order.
#Cons: Not suitable for non-ordinal data, as it implies ranking.
df['City'] = df['City'].map({'New York': 1, 'San Francisco': 2, 'Los Angeles': 3})
df.head()

   Age  Salary  Purchased  Gender  City
0   41   63159          1  Female     1
1   43   43986          0  Female     1
2   42   91858          0  Female     3
3   62   42666          0    Male     3
4   58   68660          0    Male     3

In [ ]:
# Target Encoding
#Pros: Useful for high-cardinality features.
#Cons: Can cause data leakage if target encoding is not done properly.
mean_target = df.groupby('City')['Purchased'].mean()
df['City_encoded'] = df['City'].map(mean_target)
df.head()

   Age  Salary  Purchased  Gender  City  City_encoded
0   41   63159          1  Female     1      0.333333
1   43   43986          0  Female     1      0.333333
2   42   91858          0  Female     3      0.000000
3   62   42666          0    Male     3      0.000000
4   58   68660          0    Male     3      0.000000

When you need to scale features

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# Standardization (mean=0, variance=1)
#Pros: Works well for normally distributed data; suitable for many models.
#Cons: Sensitive to outliers.
scaler = StandardScaler()
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])
df.head()

        Age    Salary  Purchased  Gender  City  City_encoded
0  0.026802 -0.496908          1  Female     1      0.333333
1  0.160810 -1.213082          0  Female     1      0.333333
2  0.093806  0.575092          0  Female     3      0.000000
3  1.433886 -1.262388          0    Male     3      0.000000
4  1.165870 -0.291428          0    Male     3      0.000000

In [ ]:


df = createdata()
df.head(5)

   Age  Salary  Purchased  Gender         City
0   50   98840          1    Male  Los Angeles
1   18   84384          1    Male  Los Angeles
2   44   81005          1  Female     New York
3   69   76576          1  Female     New York
4   30   69353          1    Male  Los Angeles

In [ ]:


# Normalization (range 0-1)
#Pros: Keeps all data between 0 and 1; ideal for distance-based models.
#Cons: Can distort data distribution, especially with extreme outliers.
normalizer = MinMaxScaler()
df[['Age', 'Salary']] = normalizer.fit_transform(df[['Age', 'Salary']])
df.head()

        Age    Salary  Purchased  Gender         City
0  0.627451  0.767163          1    Male  Los Angeles
1  0.000000  0.604040          1    Male  Los Angeles
2  0.509804  0.565911          1  Female     New York
3  1.000000  0.515933          1  Female     New York
4  0.235294  0.434428          1    Male  Los Angeles

In [ ]:
df = createdata()
df.head(5)

   Age  Salary  Purchased  Gender           City
0   19   62711          1    Male       New York
1   18   35539          1  Female       New York
2   65   83351          1  Female  San Francisco
3   29   91267          0    Male       New York
4   22   78354          0    Male  San Francisco

In [ ]:
# Robust Scaling (uses median and IQR, robust to outliers)
#Pros: More robust to outliers by using median and IQR.
#Cons: Doesn’t work as well for normal distributions.
robust_scaler = RobustScaler()
df[['Age', 'Salary']] = robust_scaler.fit_transform(df[['Age', 'Salary']])
df.head(5)

    Age    Salary  Purchased  Gender           City
0 -0.80 -0.228719          1    Male       New York
1 -0.84 -0.849573          1  Female       New York
2  1.04  0.242885          1  Female  San Francisco
3 -0.40  0.423758          0    Male       New York
4 -0.68  0.128709          0    Male  San Francisco